version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ensar1234
      MYSQL_DATABASE: EnsarDB
    ports:
      - "3307:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  mongodb:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: ensar1234
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db 

  myapi:
    build: .
    container_name: my-api
    restart: always
    ports:
      - "5000:80"
    depends_on:
      - mongodb
    environment:
      - MongoDB__ConnectionString=mongodb://mongoadmin:ensar1234@mongodb:27017
      - MongoDB__DatabaseName=UserDB

volumes:
  mongodata:
    driver: local
